package nftables

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Plugin renders nftables DNAT forward rules (Entry -> next hop).
type Plugin struct {
	DataDir string
	DryRun  bool
}

func (p *Plugin) Name() string { return "nft_forward" }

// Stop implements plugins.Stopper — drop DNAT table when removed / node revoked.
func (p *Plugin) Stop() {
	if p.DryRun {
		log.Printf("[nft_forward] stop (dry-run)")
		return
	}
	if _, err := exec.LookPath("nft"); err != nil {
		return
	}
	_ = exec.Command("nft", "delete", "table", "ip", "mieru_panel").Run()
	log.Printf("[nft_forward] table deleted")
}

func (p *Plugin) Apply(ctx context.Context, cfg map[string]interface{}) error {
	_ = ctx
	if err := os.MkdirAll(p.DataDir, 0o755); err != nil {
		return err
	}

	rawRules, _ := cfg["rules"].([]interface{})
	var b strings.Builder
	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# generated by mieru-panel agent\n")
	b.WriteString("table ip mieru_panel {\n")
	b.WriteString("  chain prerouting {\n")
	b.WriteString("    type nat hook prerouting priority dstnat; policy accept;\n")
	for _, r := range rawRules {
		m, ok := r.(map[string]interface{})
		if !ok {
			continue
		}
		lp := toInt(m["listen_port"])
		th, _ := m["target_host"].(string)
		tp := toInt(m["target_port"])
		if lp == 0 || th == "" || tp == 0 {
			continue
		}
		fmt.Fprintf(&b, "    tcp dport %d dnat to %s:%d\n", lp, th, tp)
	}
	b.WriteString("  }\n")
	b.WriteString("  chain postrouting {\n")
	b.WriteString("    type nat hook postrouting priority srcnat; policy accept;\n")
	b.WriteString("    masquerade\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")

	path := filepath.Join(p.DataDir, "nftables.mieru.nft")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	log.Printf("[nft_forward] wrote %s (%d rules)", path, len(rawRules))

	if p.DryRun {
		return nil
	}
	if _, err := exec.LookPath("nft"); err != nil {
		log.Printf("[nft_forward] nft not found; rules file only")
		return nil
	}
	_ = exec.Command("nft", "delete", "table", "ip", "mieru_panel").Run()
	cmd := exec.Command("nft", "-f", path)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nft apply: %w (%s)", err, string(out))
	}
	return nil
}

func toInt(v interface{}) int {
	switch t := v.(type) {
	case float64:
		return int(t)
	case int:
		return t
	case int64:
		return int(t)
	default:
		return 0
	}
}
